### ISSUE TITLE
Telescope extension being incorrectly drawn

### ISSUE THREAD

**Issue by bellini666** [Lyude/neovim-gtk#5] opened 2021-10-17 13:19 UTC
**Describe the bug**

I was trying to use the [telescope](https://github.com/nvim-telescope/telescope.nvim) extension and it works fine on terminal, but it is totally incorrectly drawn on neovim-gtk:

![Screenshot from 2021-10-17 10-15-55](https://user-images.githubusercontent.com/134025/137628751-96117c68-e399-47bd-a01b-dea16748c396.png)

Based on the fact that it only happens on GUI and not the terminal, I don't think the problem is with telescope itself, but I might be wrong. So either way I'm posting it here...

**Technical information (please complete the following information):**
 - OS: [e.g. Windows, Linux Ubuntu]

Linux (Debian Testing/Unstable up to date)

 - Neovim version: [e.g. .0.0.3]

Neovim 0.5.1

 - Neovim-Gtk build version: [e.g. flatpak, commit hash]

https://github.com/Lyude/neovim-gtk/commit/4e466e34c058b0c24adb2e5c96e0b574b10c7de3

**Comment by bellini666** [comment] 2021-10-17 13:20
Note that not only it draws wrong but when dismissing it, some gargage is still left in the screen (the part that was outside the "modal")

**Comment by Lyude** [comment] 2021-10-19 23:48
Hm, I wonder if https://github.com/daa84/neovim-gtk/pull/263 might be relevant here. Either way, will try to get to this issue when I have the time :)

**Comment by jacobmischka** [comment] 2021-10-20 06:49
I actually have that merged into my fork of yours as well, I can submit that PR too.

**Comment by medicalwei** [comment] 2021-10-20 23:28
I can reproduce this issue with Inconsolata font (and I can't reproduce this using Fira Code font), and confirm that the commits handling CJK can fix the Telescope UI in neovim-gtk.

**Comment by Lyude** [comment] 2021-10-31 20:48
@bellini666 @medicalwei OK - I ended up going with Yao Wei's itemizer changes, but modified them to use grapheme clusters which looks like it fixes CJK and languages like Hindi for me locally. Could you guys try b9b2201 and let me know if it still works for y'all?

**Comment by bellini666** [comment] 2021-10-31 20:54
Hey @Lyude . Just tested it here and it fixes the issue :)

**Comment by Lyude** [comment] 2021-11-01 00:27
> Hey @Lyude . Just tested it here and it fixes the issue :)

Cool! I'm going to go ahead and merge me and @medicalwei 's fixes then

**Closed** 2021-11-01 00:27 UTC
Labels: bug
